services/web/.gitignore, services/web/README.md, services/web/next-env.d.ts, services/web/package.json, services/web/src/pages/_app.tsx, services/web/src/pages/index.tsx, services/web/src/styles/globals.css, services/web/src/theme/colors/index.ts, services/web/src/theme/fonts/index.ts, services/web/src/theme/index.ts, services/web/tsconfig.json, yarn.lock
Added NextJS setup with ChakraUI + react-icons
=> Setup web project

README.md
This is the initial Readme it is expected to grow and evolve as more of the technical aspects of the project are defined
=> Initial Read Me

services/backend/.eslintrc.js, services/backend/.prettierrc, services/backend/package-lock.json, services/backend/package.json, services/backend/src/app.ts, services/web/.eslintrc.js, services/web/.prettierrc, services/web/package.json, yarn.lock
We need eslint before we start commiting app code
=> Setup Eslint + Prettier web + back

services/backend/src/app.ts, services/backend/src/controllers/ExampleController.ts, services/backend/src/routes/example.ts, services/backend/src/routes/index.ts, services/backend/tsconfig.json
With tons of comments to explain how to setup a new controller
=> Added ExampleController

services/backend/src/app.ts, services/backend/src/controllers/ExampleController.ts, services/backend/src/lib/IRoute.ts, services/backend/src/lib/Route.ts, services/backend/src/routes/example.ts, services/backend/src/routes/index.ts
Added what I hope is an easier way of defining routes.
=> Added abstraction for routes

services/backend/.eslintrc.js, services/backend/package.json, services/backend/src/app.ts, services/backend/src/controllers/UserController.ts, services/backend/src/entities/UserEntity.ts, services/backend/src/modules/Typeorm.ts, services/backend/src/routes/index.ts, services/backend/src/routes/user.ts, services/backend/src/services/UserService.ts, yarn.lock
Create User Controller, User Service, User Entity and the db connection
=> User Skeleton

services/backend/src/controllers/MeController.ts, services/backend/src/entities/RoleEntity.ts, services/backend/src/entities/UserEntity.ts, services/backend/src/routes/me.ts, services/backend/src/services/RoleService/index.ts, services/web/src/lib/auth/requirePageAuth.ts, services/web/src/lib/types/role.ts, services/web/src/pages/dashboard.tsx, services/web/src/pages/index.tsx
Se agrego en el back un endpoint para conseguir el role del usuario actual y en el front para proteger las rutas
=> Add Protected Routes front end

services/web/src/pages/registro/supervisor.tsx
registro para los supervisores en /registro/supervisor
=> registro supervisor

services/web/src/pages/registro/aliado.tsx
registro del aliado /registro/aliado
=> register ally

services/backend/src/controllers/UserController.ts, services/backend/src/lib/CurrentViewer.ts, services/backend/src/lib/ICurrentViewer.ts, services/backend/src/lib/Route.ts, services/backend/src/lib/RouteAuthRolesEnum.ts, services/backend/src/middleware/RequireAuth.ts, services/backend/src/routes/user.ts, services/backend/src/services/UserService/index.ts, services/web/package.json, services/web/src/components/contents/AdminIndexPageContent/UsersTable/index.tsx, services/web/src/components/contents/AdminIndexPageContent/helpers.ts, services/web/src/components/contents/AdminIndexPageContent/index.tsx, services/web/src/fetchers/index.ts, services/web/src/pages/admin/index.tsx, yarn.lock
Se agregó una vista para ver a todos los usuarios y para habilitar a supervisores
closes #12 
closes #11 
closes #16
=> Superadmin

services/web/src/components/contents/ExampleTestExcelContent/index.tsx, services/web/src/components/modules/ExcelUploaderSection/FileInfo/index.tsx, services/web/src/components/modules/ExcelUploaderSection/index.tsx, services/web/src/components/modules/ExcelUploaderSection/types.ts, services/web/src/pages/example-test/excel.tsx
Added component that let's you specify a URL and an HTTP method to upload an excel file.
=> Added component to upload excel file

services/backend/src/modules/Typeorm.ts, services/web/src/components/contents/AdminIndexPageContent/index.tsx, services/web/src/components/contents/AdminUsersLoadFromExcelContent/index.tsx, services/web/src/components/modules/Navbar/index.tsx, services/web/src/lib/routes/index.tsx, services/web/src/pages/admin/users/load-from-excel.tsx
=> Added page to load users from excel

services/backend/src/controllers/AllyController.ts, services/backend/src/entities/AllyEntity.ts, services/backend/src/modules/Typeorm.ts, services/backend/src/routes/ally.ts, services/backend/src/routes/index.ts, services/backend/src/services/AllyService/ICreateArgs.ts, services/backend/src/services/AllyService/index.ts, services/web/src/components/contents/AlliesIndexPageContent/AlliesTable/index.tsx, services/web/src/components/contents/AlliesIndexPageContent/index.tsx, services/web/src/components/layouts/PrivateLayout/index.tsx, services/web/src/lib/types/ally.ts, services/web/src/pages/allies/index.tsx
=> Table de Allies en el front

services/backend/src/controllers/GradeController.ts, services/backend/src/controllers/StudentController.ts, services/backend/src/entities/AllyEntity.ts, services/backend/src/entities/CourseEntity.ts, services/backend/src/entities/GradeEntity.ts, services/backend/src/entities/StudentEntity.ts, services/backend/src/modules/Typeorm.ts, services/backend/src/routes/grade.ts, services/backend/src/routes/index.ts, services/backend/src/routes/student.ts, services/backend/src/services/GradeService/ICreateArgs.ts, services/backend/src/services/GradeService/IUpdateArgs.ts, services/backend/src/services/GradeService/index.ts, services/backend/src/services/StudentService/ICreateArgs.ts, services/backend/src/services/StudentService/index.ts
=> Ents de Grade y Students, Controllers, Services y rutas

services/backend/src/controllers/UserController.ts, services/backend/src/routes/user.ts, services/web/src/components/contents/AdminIndexPageContent/UsersTable/index.tsx
como superadmin puedo habilitar o deshabilitar cuenta de cualquier tipo de usuario que no sea superadmin
=> habilitar tutores como superadmin

services/backend/src/controllers/SeasonController.ts, services/backend/src/routes/season.ts, services/backend/src/services/SeasonService/index.ts, services/web/src/components/contents/AlliesIndexPageContent/index.tsx, services/web/src/components/contents/SeasonsIndexPageContent/Header/index.tsx, services/web/src/components/contents/SeasonsIndexPageContent/NoSeasonsText/index.tsx, services/web/src/components/contents/SeasonsIndexPageContent/SeasonCard/index.tsx, services/web/src/components/contents/SeasonsIndexPageContent/index.tsx, services/web/src/components/modules/ErrorMessage/index.tsx, services/web/src/components/modules/LoadingSpinner/index.tsx, services/web/src/lib/routes/index.tsx, services/web/src/pages/seasons/index.tsx
_"Ver detalle" button has no functionality yet_
=> Added seasons index page

services/backend/src/controllers/AllyController.ts, services/backend/src/entities/AllyEntity.ts, services/backend/src/entities/UserEntity.ts, services/backend/src/routes/ally.ts, services/web/src/components/contents/AlliesIndexPageContent/AlliesForm/index.tsx, services/web/src/components/contents/AlliesIndexPageContent/AlliesFormCreate/index.tsx, services/web/src/components/contents/AlliesIndexPageContent/index.tsx, services/web/src/lib/types/ally.ts
=> Crear aliados individualmente 

.gitignore, services/backend/src/constants/guides.ts, services/backend/src/constants/index.ts, services/backend/src/controllers/BaseController.ts, services/backend/src/controllers/GuidesController.ts, services/backend/src/middleware/GuideFileUpload.ts, services/backend/src/routes/guide.ts, services/backend/src/routes/index.ts, services/web/src/components/contents/GuidesIndexPageContent/DownloadCard/DownloadButton/index.tsx, services/web/src/components/contents/GuidesIndexPageContent/DownloadCard/UploadButton/index.tsx, services/web/src/components/contents/GuidesIndexPageContent/DownloadCard/index.tsx, services/web/src/components/contents/GuidesIndexPageContent/HeaderContent/index.tsx, services/web/src/components/contents/GuidesIndexPageContent/index.tsx, services/web/src/lib/routes/index.tsx, services/web/src/pages/guides/index.tsx, services/web/src/pages/registro/aliado.tsx
=> Added guides uploading and downloading

services/backend/src/routes/guide.ts
Anyone should be able to download guides
=> Allow anyone to download guides

services/backend/src/controllers/AllyController.ts, services/backend/src/routes/ally.ts, services/backend/src/services/AllyService/index.ts, services/web/src/components/contents/AlliesPublicPageContent/AlliesStudentForm/index.tsx, services/web/src/components/contents/AlliesPublicPageContent/AlliesStudentFormCreate/index.tsx, services/web/src/components/contents/AlliesPublicPageContent/StudentTableDisplay/index.tsx, services/web/src/components/contents/AlliesPublicPageContent/StudentsTable/index.tsx, services/web/src/components/contents/AlliesPublicPageContent/index.tsx, services/web/src/components/contents/LoginPageContent/index.tsx, services/web/src/lib/types/student.ts, services/web/src/pages/aliados.tsx
=> Vista de Estudiantes de un Aliado

services/web/src/components/contents/AlliesIndexPageContent/AlliesForm/index.tsx
=> Agregar validacion de aliado al subir individual

services/web/src/components/contents/DashboardPageContent/index.tsx, services/web/src/pages/dashboard.tsx
=> Simple welcome page

services/backend/src/controllers/UserController.ts, services/backend/src/entities/StudentCourseEntity.ts, services/backend/src/modules/Typeorm.ts, services/backend/src/services/StudentCourseService/ICreateArgs.ts, services/backend/src/services/StudentCourseService/index.ts, services/backend/src/services/StudentService/index.ts
=> Connect students to courses from excel

services/backend/src/controllers/CourseController.ts, services/backend/src/routes/courses.ts, services/backend/src/services/SupervisorCourseService/IFindCoursesForUser.ts, services/backend/src/services/SupervisorCourseService/index.ts, services/backend/src/services/TutorCourseService/index.ts, services/web/src/components/contents/MyCoursesPageContent/CourseCard/index.tsx, services/web/src/components/contents/MyCoursesPageContent/index.tsx, services/web/src/lib/routes/index.tsx, services/web/src/pages/supervisor/courses.tsx
=> See coourses as supervisor

services/backend/src/controllers/CourseController.ts, services/backend/src/routes/courses.ts, services/web/src/lib/routes/index.tsx, services/web/src/pages/tutor/courses.tsx
=> Cursos del tutor

services/web/src/components/contents/AlliesPublicPageContent/StudentTableDisplay/index.tsx
=> Usar student table de mycourses para mostrar "califas"

services/web/src/components/modules/Navbar/index.tsx
=> Show role in nav bar

services/backend/src/controllers/CourseController.ts, services/backend/src/routes/courses.ts, services/backend/src/services/CourseService/IGetTutorsArgs.ts, services/backend/src/services/CourseService/index.ts, services/backend/src/services/SupervisorCourseService/IUserOwnerOfCourse.ts, services/backend/src/services/SupervisorCourseService/index.ts, services/backend/src/services/TutorCourseService/index.ts, services/web/src/components/contents/CoursePageContent/TutorsInCourse/TutorsTable/index.tsx, services/web/src/components/contents/CoursePageContent/TutorsInCourse/index.tsx, services/web/src/components/contents/CoursePageContent/index.tsx, services/web/src/components/contents/MyCoursesPageContent/CourseCard/index.tsx, services/web/src/components/contents/MyCoursesPageContent/index.tsx, services/web/src/pages/supervisor/courses/index.tsx, services/web/src/pages/tutor/courses/index.tsx
Ver arriba también para ver en curso individual como ya no sale el URL
=> Added tutors in supervisor course page, removed URL from courses, added

services/backend/src/controllers/SeasonController.ts, services/backend/src/routes/season.ts, services/backend/src/services/SeasonService/IFindCoursesArgs.ts, services/backend/src/services/SeasonService/index.ts, services/web/src/components/contents/CoursesBySeasonPageContent/index.tsx, services/web/src/components/contents/CoursesPageContent/CoursesTable/index.tsx, services/web/src/components/contents/SeasonsIndexPageContent/SeasonCard/index.tsx, services/web/src/pages/seasons/[seasonID].tsx
when clicking on ver cursos
changed the order of this table:
removed url from courses table:
=> Option to see courses by season for the superadmin

services/backend/src/controllers/StudentController.ts, services/backend/src/routes/student.ts, services/backend/src/services/StudentService/index.ts, services/web/src/components/contents/AdminStudentsIndexPageContent/StudentsTable/index.tsx, services/web/src/components/contents/AdminStudentsIndexPageContent/index.tsx, services/web/src/lib/routes/index.tsx, services/web/src/pages/admin/students/index.tsx
=> Add students page for superadmin

services/backend/src/controllers/CourseController.ts, services/backend/src/controllers/GradeController.ts, services/backend/src/controllers/StudentController.ts, services/backend/src/entities/CourseEntity.ts, services/backend/src/entities/GradeEntity.ts, services/backend/src/routes/grade.ts, services/backend/src/routes/student.ts, services/backend/src/services/GradeService/index.ts, services/backend/src/services/StudentService/IGetCourseGrade.ts, services/backend/src/services/StudentService/IGetGradesByCourse.ts, services/backend/src/services/StudentService/index.ts, services/web/src/components/contents/MyCoursesPageContent/CourseStudent/index.tsx, services/web/src/components/contents/MyCoursesPageContent/GradeModal/index.tsx, services/web/src/components/contents/MyCoursesPageContent/StudentGradeModal/index.tsx, services/web/src/components/contents/MyCoursesPageContent/StudentGradeTable/index.tsx, services/web/src/components/contents/MyCoursesPageContent/StudentsTable/index.tsx, services/web/src/components/contents/TutorCoursesStudentsPageContent/StudentGradeModal/index.tsx, services/web/src/components/contents/TutorCoursesStudentsPageContent/StudentsTable/index.tsx, services/web/src/components/modules/ExcelUploaderSection/index.tsx
=> Calificar, ver califas como tutor, supervisor y aliado

services/web/src/components/contents/AdminIndexPageContent/UsersTable/index.tsx, services/web/src/components/contents/AdminStudentsIndexPageContent/StudentsTable/index.tsx, services/web/src/components/contents/AlliesIndexPageContent/AlliesTable/index.tsx, services/web/src/components/contents/CoursesPageContent/CoursesTable/index.tsx, services/web/src/components/contents/MyCoursesPageContent/StudentsTable/index.tsx
=> Table order

services/backend/src/controllers/CourseController.ts, services/backend/src/entities/CourseEntity.ts, services/backend/src/services/CourseService/ICreateArgs.ts, services/backend/src/services/CourseService/index.ts
Ahora se guarda correctamente,
tambien se arreglaron unos errores que tiraba al momento de crear
=> Fix activities en cursos
